# the code for this .Travis.yml has been mostly taken from https://github.com/haiwen/seafile-docker/blob/master/.travis.yml
language: python
python:
  - "2.7"
env:
  global:
    - "HOST_IP=$(/sbin/ifconfig venet0:0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')"
    - DOCKER_HOST=tcp://$HOST_IP:2375
    - SLIRP_PORTS="2375 4445"
    - TEST_ENV=travis
services: mongodb
before_install:
  - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
  - sudo chmod +x /usr/sbin/policy-rc.d
  - pip install --upgrade pip
install:
  - curl -sSL https://get.docker.com/ | sh
  - sudo apt-get install slirp libtidy-* xvfb
  - sudo usermod -aG docker "$USER"
  - git clone git://github.com/cptactionhank/sekexe
  - pip install --process-dependency-links --upgrade .
  - sudo mkdir /var/lib/docker
  - sudo mkdir /etc/docker
  - sudo chmod -R 777 /var/lib/docker
  - sudo chmod -R 777 /etc/docker
  - sudo mkdir /agent_volume
before_script:
  - "sudo HOST_IP=\"$HOST_IP\" SLIRP_PORTS=\"$SLIRP_PORTS\" sekexe/run 'mount -t tmpfs -o size=8g tmpfs /var/lib/docker && docker -d --log-level=error -H tcp://0.0.0.0:2375' &"
  - "while ! docker info; do echo 'retrying to connect to docker...'; sleep 1; done"
  - docker pull centos
  - docker pull ingi/inginious-c-default
script:
  - python setup.py test


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ca35676eddd3efe5a17f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
