backend: tcp://backend:2000
backup_directory: /inginious/backups
local-config: {}
mongo_opt:
    database: INGInious
    host: db
plugins: []
session_parameters:
    ignore_change_ip: false
    secret_key: 96f4628a2e4d0ce26b6352713f8ac8359b838f4800f1972790622899664bd0f4
    secure: false
    timeout: 86400
superadmins:
- superadmin
tasks_directory: /inginious/tasks
use_minified_js: true
